/**
 * Selectors over `ParserState` — the only sanctioned way UI reads node data
 * (ANTI_CHAOS Rule 11's Selector Pattern boundary). Each selector is a small,
 * pure function returning a ready View Model; none compute a new score or
 * validity here — sorting/filtering on a value already computed by
 * Validation/Analyzer is display, not Core logic, so it is allowed in this
 * boundary layer. Computing a NEW score/validity belongs in
 * `core/validator/`/`core/analyzer/`, never here.
 *
 * Memoizing a selector's result across renders (Render Optimization Rules,
 * spec 13) is the `ui/store/` Preact bridge's job, not this file's — these
 * functions stay plain and framework-agnostic.
 *
 * @typedef {import("../types/unm").UNMNode} UNMNode
 * @typedef {import("../types/unm").Protocol} Protocol
 * @typedef {import("./parser-state").ParserState} ParserState
 * @typedef {import("./analyzer-state").AnalyzerState} AnalyzerState
 * @typedef {import("../analyzer/analyze-node.js").AnalysisBundle} AnalysisBundle
 */

/**
 * @param {ParserState} state
 * @returns {readonly UNMNode[]}
 */
export function selectAllNodes(state) {
  return state.nodes;
}

/**
 * @param {ParserState} state
 * @param {string} nodeId
 * @returns {UNMNode | undefined}
 */
export function selectNodeById(state, nodeId) {
  return state.nodes.find((n) => n.nodeId === nodeId);
}

/**
 * @param {ParserState} state
 * @returns {readonly string[]}
 */
export function selectValidNodeIds(state) {
  return state.nodes.filter((n) => n.validation.overallValid).map((n) => n.nodeId);
}

/**
 * Sorted by `analysis.securityScore` (Analyzer-computed, ADR-011), highest
 * first. Nodes the Analyzer has not yet scored (`analysis` absent) sort
 * last, not first — an unscored node is not implied to be insecure.
 * @param {ParserState} state
 * @returns {readonly UNMNode[]}
 */
export function selectNodesSortedBySecurity(state) {
  return [...state.nodes].sort((a, b) => {
    const scoreA = a.analysis?.securityScore;
    const scoreB = b.analysis?.securityScore;
    if (scoreA === undefined && scoreB === undefined) return 0;
    if (scoreA === undefined) return 1;
    if (scoreB === undefined) return -1;
    return scoreB - scoreA;
  });
}

/**
 * Count nodes per `protocol` (Converter Screen's Parser Preview "Protocol
 * Count", doc 07 §4.2) — a tally of an already-set field, not a new
 * classification.
 * @param {ParserState} state
 * @returns {Readonly<Record<string, number>>}
 */
export function selectProtocolCounts(state) {
  /** @type {Record<string, number>} */
  const counts = {};
  for (const n of state.nodes) {
    counts[n.protocol] = (counts[n.protocol] || 0) + 1;
  }
  return counts;
}

/**
 * Flatten `metadata.warnings` across every node (Parser Preview "Warnings",
 * doc 07 §4.2) — concatenation of values the Parser already produced.
 * @param {ParserState} state
 * @returns {readonly string[]}
 */
export function selectAggregatedWarnings(state) {
  return state.nodes.flatMap((n) => n.metadata.warnings);
}

/**
 * Flatten `metadata.errors` across every node (Parser Preview "Errors",
 * doc 07 §4.2).
 * @param {ParserState} state
 * @returns {readonly string[]}
 */
export function selectAggregatedErrors(state) {
  return state.nodes.flatMap((n) => n.metadata.errors);
}

/**
 * Flatten `metadata.recoveryActions` across every node (Converter Screen's
 * "Recovery Actions" section, doc 07 §4.2 — "این اطلاعات از قبل در
 * metadata.recoveryActions وجود دارد؛ این بخش فقط نمایش آن در UI است").
 * @param {ParserState} state
 * @returns {readonly string[]}
 */
export function selectAggregatedRecoveryActions(state) {
  return state.nodes.flatMap((n) => n.metadata.recoveryActions);
}

/**
 * Look up one node's Analyzer verdict bundle (Analyzer Screen, doc 07 §4.3)
 * from `AnalyzerState` — a separate domain store from `ParserState`, see
 * `core/store/analyzer-state.js` for why the bundle is not on `node.analysis`.
 * @param {AnalyzerState} state
 * @param {string} nodeId
 * @returns {AnalysisBundle | undefined}
 */
export function selectAnalysisByNodeId(state, nodeId) {
  return state.analysisByNodeId[nodeId];
}

/**
 * Sort nodes by recency, most recent first (Dashboard's "Recent Imports",
 * doc 07 §4.1). `createdAt` is always internally generated by `createNode`
 * (Rule 4, ISO 8601, lexicographically sortable as-is) — never user input —
 * so this only orders an already-trustworthy value, it does not derive one.
 * Scoped to the CURRENT session's nodes: no Phase 9 screen writes to the
 * durable `core/storage/` yet, so there is no cross-session import history
 * to sort here.
 * @param {ParserState} state
 * @returns {readonly UNMNode[]}
 */
export function selectNodesSortedByCreatedAt(state) {
  return [...state.nodes].sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

/**
 * Average `security.securityScore` across every node the Analyzer has
 * scored so far (Dashboard's "Health Overview", doc 07 §4.1). `null` when
 * nothing has been analyzed yet — never fabricated as 0 (Rule 9).
 * @param {AnalyzerState} state
 * @returns {number | null}
 */
export function selectAverageSecurityScore(state) {
  const scores = Object.values(state.analysisByNodeId).map((a) => a.security.securityScore);
  if (scores.length === 0) return null;
  return scores.reduce((sum, s) => sum + s, 0) / scores.length;
}

/**
 * Full-text search across the identity fields every node always has
 * (Subscription Center's "Search Nodes", doc 07 §4.4 / doc 03 §2.1).
 * `remark`/`group`/`tags` (spec 05 §2) are real UNMNode fields but no parser
 * populates them yet, so searching them today would always miss — scoped to
 * `protocol`/`address`/`port` instead. Case-insensitive substring match; a
 * blank query returns every node, not none.
 * @param {ParserState} state
 * @param {string} query
 * @returns {readonly UNMNode[]}
 */
export function selectNodesMatchingSearch(state, query) {
  const q = query.trim().toLowerCase();
  if (q === "") return state.nodes;
  return state.nodes.filter(
    (n) =>
      n.protocol.toLowerCase().includes(q) ||
      n.address.toLowerCase().includes(q) ||
      String(n.port).includes(q),
  );
}

/**
 * Narrow to one protocol (Subscription Center's "Filter", doc 07 §4.4).
 * `"all"` is the no-op case, returning every node.
 * @param {ParserState} state
 * @param {Protocol | "all"} protocol
 * @returns {readonly UNMNode[]}
 */
export function selectNodesFilteredByProtocol(state, protocol) {
  if (protocol === "all") return state.nodes;
  return state.nodes.filter((n) => n.protocol === protocol);
}

/**
 * Narrow by the Validation Engine's `overallValid` verdict (Subscription
 * Center's "Filter", doc 07 §4.4). `"all"` is the no-op case.
 * @param {ParserState} state
 * @param {"valid" | "invalid" | "all"} validity
 * @returns {readonly UNMNode[]}
 */
export function selectNodesFilteredByValidity(state, validity) {
  if (validity === "all") return state.nodes;
  const wantValid = validity === "valid";
  return state.nodes.filter((n) => n.validation.overallValid === wantValid);
}

/**
 * Generic ascending/descending sort over one of the few fields every node
 * always has (Subscription Center's "Sort", doc 07 §4.4) — the same
 * reorder-only boundary as `selectNodesSortedByCreatedAt`/
 * `selectNodesSortedBySecurity` above, just parameterized over field and
 * direction instead of one fixed field.
 * @param {ParserState} state
 * @param {"protocol" | "address" | "port" | "createdAt"} field
 * @param {"asc" | "desc"} direction
 * @returns {readonly UNMNode[]}
 */
export function selectNodesSortedByField(state, field, direction) {
  const sign = direction === "asc" ? 1 : -1;
  return [...state.nodes].sort((a, b) => {
    const va = a[field];
    const vb = b[field];
    if (va < vb) return -1 * sign;
    if (va > vb) return 1 * sign;
    return 0;
  });
}

/**
 * Group nodes by `protocol` (Subscription Center's "Group", doc 07 §4.4) —
 * the only grouping field every node reliably has today; `group` (spec 05
 * §2) exists on UNMNode but no parser populates it yet, so grouping by it
 * would always collapse to a single bucket.
 * @param {ParserState} state
 * @returns {Readonly<Record<string, readonly UNMNode[]>>}
 */
export function selectNodesGroupedByProtocol(state) {
  /** @type {Record<string, UNMNode[]>} */
  const groups = {};
  for (const n of state.nodes) {
    (groups[n.protocol] ??= []).push(n);
  }
  return groups;
}
